openapi: 3.0.0
info:
  title: XenElectronic Core API
  description: API endpoints for XenElectronic Core
  version: '0.0.1'
tags:
  - name: xenelectronic-core
    description: Endpoints for XenElectronic Core
security:
  - apiKeyAuth: []
  - bearerAuth: []

paths:
  /api/v1/version:
    summary: Returns the current version
    get:
      tags:
        - xenelectronic-core
      responses:
        200:
          description: The API version
          content:
            application/json:
              schema:
                type: object
                properties:
                  version:
                    type: string
                    example: '1.0'
        default:
          $ref: '#/components/responses/jsonError'

  /api/v1/health:
    summary: Health check
    get:
      tags:
        - xenelectronic-core
      responses:
        200:
          description: An empty response body.
          content:
            application/json:
              schema:
                type: object
                properties:
                  version:
                    type: string
                    example: '1.0'
        default:
          $ref: '#/components/responses/jsonError'

components:
  securitySchemes:
    apiKeyAuth:
      type: apiKey
      in: header
      name: API-KEY
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  responses:
    jsonError:
      description: >-
        A detailed JSON errors will be returned when there's an issue calling the
        endpoint.
      content:
        application/json:
          schema:
            type: array
            items:
              allOf:
                - $ref: '#/components/schemas/Error'
