// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/YannaAlghamdi/xenelectronic/core/config"
	"github.com/YannaAlghamdi/xenelectronic/core/db"
	"github.com/YannaAlghamdi/xenelectronic/core/db/migrations"
	"github.com/YannaAlghamdi/xenelectronic/core/handlers"
	"github.com/YannaAlghamdi/xenelectronic/core/internal/models"
	"github.com/YannaAlghamdi/xenelectronic/core/internal/services"
	"github.com/google/wire"
)

// Injectors from wire.go:

func buildServer(cfg *config.Config) (Server, error) {
	postgresClient := db.NewPostgresClient(cfg)
	categoryRepository := models.NewCategoryRepository(postgresClient)
	categoryService := services.NewCategoryService(categoryRepository)
	categoryHandler := handler.NewCategoryHandler(categoryService)
	mainServer := CreateServer(cfg, categoryHandler)
	return mainServer, nil
}

func initializeMigration(cfg *config.Config) (migrations.Migration, error) {
	postgresClient := db.NewPostgresClient(cfg)
	migration := migrations.NewMigration(cfg, postgresClient)
	return migration, nil
}

// wire.go:

var DependencySet = wire.NewSet(
	CreateServer, models.NewProductRespository, models.NewCategoryRepository, models.NewCartRepository, services.NewCartService, services.NewCategoryService, handler.NewCategoryHandler, db.NewPostgresClient, wire.Bind(new(db.DBClient), new(*db.PostgresClient)),
)

var MigrationSet = wire.NewSet(migrations.NewMigration, db.NewPostgresClient, wire.Bind(new(db.DBClient), new(*db.PostgresClient)))
