// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/YannaAlghamdi/xenelectronic/core/config"
	"github.com/YannaAlghamdi/xenelectronic/core/db"
	"github.com/YannaAlghamdi/xenelectronic/core/db/migrations"
	"github.com/YannaAlghamdi/xenelectronic/core/handlers"
	"github.com/YannaAlghamdi/xenelectronic/core/internal/models"
	"github.com/YannaAlghamdi/xenelectronic/core/internal/services"
	"github.com/google/wire"
)

// Injectors from wire.go:

func buildServer(cfg *config.Config) (Server, error) {
	postgresClient := db.NewPostgresClient(cfg)
	categoryRepository := models.NewCategoryRepository(postgresClient)
	categoryService := services.NewCategoryService(categoryRepository)
	categoryHandler := handler.NewCategoryHandler(categoryService)
	productRepository := models.NewProductRespository(postgresClient)
	productService := services.NewProductService(productRepository)
	productHandler := handler.NewProductHandler(productService)
	cartRepository := models.NewCartRepository(postgresClient)
	cartService := services.NewCartService(cartRepository)
	cartHandler := handler.NewCartHandler(cartService)
	orderRepository := models.NewOrderRepository(postgresClient)
	orderService := services.NewOrderService(orderRepository)
	orderHandler := handler.NewOrderHandler(orderService)
	mainServer := CreateServer(cfg, categoryHandler, productHandler, cartHandler, orderHandler)
	return mainServer, nil
}

func initializeMigration(cfg *config.Config) (migrations.Migration, error) {
	postgresClient := db.NewPostgresClient(cfg)
	migration := migrations.NewMigration(cfg, postgresClient)
	return migration, nil
}

// wire.go:

var DependencySet = wire.NewSet(
	CreateServer, models.NewProductRespository, models.NewCategoryRepository, models.NewCartRepository, models.NewOrderRepository, services.NewCartService, services.NewProductService, services.NewCategoryService, services.NewOrderService, handler.NewOrderHandler, handler.NewCategoryHandler, handler.NewProductHandler, handler.NewCartHandler, db.NewPostgresClient, wire.Bind(new(db.DBClient), new(*db.PostgresClient)),
)

var MigrationSet = wire.NewSet(migrations.NewMigration, db.NewPostgresClient, wire.Bind(new(db.DBClient), new(*db.PostgresClient)))
